USE [master]
SELECT TOP 1 Name FROM sys.certificates WHERE name LIKE 'RDSTDECertificate%'

USE [master]
CREATE DATABASE MyDatabase

Use [MyDatabase]
CREATE DATABASE ENCRYPTION KEY WITH ALGORITHM = AES_128 ENCRYPTION BY SERVER CERTIFICATE <<PUT_NAME_HERE>>
ALTER DATABASE MyDatabase SET ENCRYPTION ON
